アノテーションによるコンポーネント登録
nablarch/nablarch-core-repository pull request #16
Opened 2020-07-14 01:52 UTC by kumagoro1202

2020-07-14 08:04 UTC, backpaper0 requested changes

2020-07-14 08:04 UTC, backpaper0 commented on src/main/java/nablarch/core/repository/di/config/ConstructorInjectionComponentCreator.java
> +        Constructor<?>[] constructors = def.getType().getDeclaredConstructors();
`public`なコンストラクタだけ相手にすれば良いので`getConstructors`を使ってください。

`getDeclaredConstructors`と`getConstructors`の違いは次の通り。

```
$ jshell
|  JShellへようこそ -- バージョン11.0.7
|  概要については、次を入力してください: /help intro

jshell> public class Demo {
   ...> public Demo(byte b) {}
   ...> protected Demo(short s) {}
   ...> Demo(int i) {}
   ...> private Demo(long l) {}
   ...> }
|  次を作成しました: クラス Demo

jshell> Demo.class.getDeclaredConstructors().length
$2 ==> 4

jshell> Demo.class.getConstructors().length
$3 ==> 1

jshell> Demo.class.getConstructors()[0]
$4 ==> public Demo(byte)

jshell> /exit
|  終了します
$
```

2020-07-14 08:04 UTC, backpaper0 commented on src/main/java/nablarch/core/repository/di/config/ConstructorInjectionComponentCreator.java
> +                return getReferenceComponent(container, ((ComponentRef) annotation));
キャスト付近に余分な括弧があります。

2020-07-14 08:04 UTC, backpaper0 commented on src/main/java/nablarch/core/repository/di/config/ConstructorInjectionComponentCreator.java
> +    private Object getComponent(DiContainer container, Class<?> type, Annotation[] annotations) {
`ConfigValue`と`ComponentRef`の両方が付いていたらエラーにしたいです。

2020-07-14 08:04 UTC, backpaper0 commented on src/main/java/nablarch/core/repository/di/config/ConstructorInjectionComponentCreator.java
> +        return component;
型が合っていない場合、`ClassCastException`がスローされます。
明示的に型チェックをしてあげた方がわかりやすいと思います。

2020-07-14 08:04 UTC, backpaper0 commented on src/main/java/nablarch/core/repository/di/config/externalize/AnnotationComponentDefinitionLoader.java
> +        private final ComponentCreator componentCreator = new ConstructorInjectionComponentCreator();
`AnnotationComponentDefinitionLoader`に次のような`protected`メソッドを用意して、

```
    protected ComponentCreator newComponentCreator() {
        return new ConstructorInjectionComponentCreator();
    }
```

次のように`ResourceClassHandler`インスタンスを作ってあげると`ComponentCreator`も差し替えられて拡張性が高くなると思いました。

```
ResourceClassHandler classHandler = new ResourceClassHandler(container, newComponentCreator());
```

2020-07-14 08:04 UTC, backpaper0 commented on src/main/java/nablarch/core/repository/di/config/ConstructorInjectionComponentCreator.java
> +        if (!(component instanceof String)) {
XMLの`<property/>`だと`boolean`や`int`の値もインジェクションできる気がするんですが、あれってどういう仕組みなんでしたっけ？

この仕組みだと`String`しかインジェクションできなくて若干不便だな、と思っていました。

2020-07-15 07:10 UTC, kumagoro1202 commented on src/main/java/nablarch/core/repository/di/config/ConstructorInjectionComponentCreator.java
> +        Constructor<?>[] constructors = def.getType().getDeclaredConstructors();
https://github.com/nablarch/nablarch-core-repository/pull/16/commits/0b01f8e04b104b9ceecd97b571bacf74639b539b#diff-82d67eef73e113773f8d9ee986a35bc9R21

2020-07-15 07:11 UTC, kumagoro1202 commented on src/main/java/nablarch/core/repository/di/config/ConstructorInjectionComponentCreator.java
> +                return getReferenceComponent(container, ((ComponentRef) annotation));
https://github.com/nablarch/nablarch-core-repository/pull/16/commits/0b01f8e04b104b9ceecd97b571bacf74639b539b#diff-82d67eef73e113773f8d9ee986a35bc9R89

2020-07-15 07:11 UTC, kumagoro1202 commented on src/main/java/nablarch/core/repository/di/config/ConstructorInjectionComponentCreator.java
> +    private Object getComponent(DiContainer container, Class<?> type, Annotation[] annotations) {
https://github.com/nablarch/nablarch-core-repository/pull/16/commits/0b01f8e04b104b9ceecd97b571bacf74639b539b#diff-82d67eef73e113773f8d9ee986a35bc9R79-R94

2020-07-15 07:11 UTC, kumagoro1202 commented on src/main/java/nablarch/core/repository/di/config/ConstructorInjectionComponentCreator.java
> +        return component;
https://github.com/nablarch/nablarch-core-repository/pull/16/commits/0b01f8e04b104b9ceecd97b571bacf74639b539b#diff-82d67eef73e113773f8d9ee986a35bc9R126-R131

2020-07-15 07:12 UTC, kumagoro1202 commented on src/main/java/nablarch/core/repository/di/config/externalize/AnnotationComponentDefinitionLoader.java
> +        private final ComponentCreator componentCreator = new ConstructorInjectionComponentCreator();
https://github.com/nablarch/nablarch-core-repository/pull/16/commits/0b01f8e04b104b9ceecd97b571bacf74639b539b#diff-32ef110c638e6fa5b450e8452bfcf76cR55-R58

2020-07-15 07:13 UTC, kumagoro1202 commented on src/main/java/nablarch/core/repository/di/config/ConstructorInjectionComponentCreator.java
> +        if (!(component instanceof String)) {
https://github.com/nablarch/nablarch-core-repository/pull/16/commits/0b01f8e04b104b9ceecd97b571bacf74639b539b#diff-82d67eef73e113773f8d9ee986a35bc9R105-R109

2020-07-15 07:13 UTC, kumagoro1202 commented on src/main/java/nablarch/core/repository/di/config/ConstructorInjectionComponentCreator.java
> +        if (!(component instanceof String)) {
https://github.com/nablarch/nablarch-core-repository/pull/16/commits/0b01f8e04b104b9ceecd97b571bacf74639b539b#diff-4ae9f6e914b13bb2ae2a6b7639acc550R20-R25

2020-07-15 07:16 UTC, kumagoro1202 commented on src/main/java/nablarch/core/repository/di/config/ConstructorInjectionComponentCreator.java
> +        Constructor<?>[] constructors = def.getType().getDeclaredConstructors();
publicなコンストラクタだけにしたため、以下の部分がテストで通せませんが何かやり方ありますか？privateメソッドでありえないパターンなのでテストなくても問題ないかと思いますが。
https://github.com/nablarch/nablarch-core-repository/pull/16/commits/0b01f8e04b104b9ceecd97b571bacf74639b539b#diff-82d67eef73e113773f8d9ee986a35bc9R52

2020-07-15 08:19 UTC, backpaper0 commented on src/main/java/nablarch/core/repository/di/config/ConstructorInjectionComponentCreator.java
> +        Constructor<?>[] constructors = def.getType().getDeclaredConstructors();
無理やりテスト通す方がおかしいのでこのままで良いです。

2020-07-15 08:45 UTC, backpaper0 commented on src/main/java/nablarch/core/repository/di/config/ConstructorInjectionComponentCreator.java
> +    private Object getComponent(DiContainer container, Class<?> type, Annotation[] annotations) {
やろうとしていることはわかるけれど1つの`for`の中で仕事をしすぎていて、読みづらいのではないかな、と思いました。

こんな感じで良いんじゃないかなと。

```java
        ConfigValue configValue = null;
        ComponentRef componentRef = null;
        for (Annotation annotation : annotations) {
            if (annotation instanceof ConfigValue) {
                configValue = (ConfigValue) annotation;
            } else if (annotation instanceof ComponentRef) {
                componentRef = (ComponentRef) annotation;
            }
        }
        if (configValue != null && componentRef != null) {
            throw new IllegalConfigurationException("both @ConfigValue and @ComponentRef are set.");
        }
        if (configValue != null) {
            return getConfigValueComponent(container, type, configValue);
        }
        if (componentRef != null) {
            return getReferenceComponent(container, type, componentRef);
        }
        return container.getComponentByType(type);
```

2020-07-15 08:50 UTC, backpaper0 commented on src/main/java/nablarch/core/repository/di/config/ConstructorInjectionComponentCreator.java
> +        return component;
このコードが絶対にNGというわけではないけれど、用途的にも`Class.isInstance`の方が合ってるように思います。

2020-07-15 08:51 UTC, backpaper0 requested changes
見ました。

2020-07-16 00:32 UTC, kumagoro1202 commented on src/main/java/nablarch/core/repository/di/config/ConstructorInjectionComponentCreator.java
> +    private Object getComponent(DiContainer container, Class<?> type, Annotation[] annotations) {
https://github.com/nablarch/nablarch-core-repository/pull/16/commits/ef4f8b4f609d946d57f34bcdd1ded8510d834351#diff-82d67eef73e113773f8d9ee986a35bc9R77-R93

2020-07-16 00:33 UTC, kumagoro1202 commented on src/main/java/nablarch/core/repository/di/config/ConstructorInjectionComponentCreator.java
> +        Constructor<?>[] constructors = def.getType().getDeclaredConstructors();
了解です。

2020-07-16 00:34 UTC, kumagoro1202 commented on src/main/java/nablarch/core/repository/di/config/ConstructorInjectionComponentCreator.java
> +        return component;
https://github.com/nablarch/nablarch-core-repository/pull/16/commits/d6e6a2d5d82c6cc5ecd924d37d3afabc3e596fe6#diff-82d67eef73e113773f8d9ee986a35bc9R126

2020-07-16 00:51 UTC, backpaper0 commented on src/main/java/nablarch/core/repository/di/config/ConstructorInjectionComponentCreator.java
> +     * @param annotation アノテーション
`type`の`@param`がないです。

2020-07-16 00:55 UTC, backpaper0 commented on src/main/java/nablarch/core/repository/di/config/externalize/AnnotationComponentDefinitionLoader.java
> +        for (Resources resources : ResourcesUtil.getResourcesTypes(basePackage)) {
ここで直接`getBasePackage()`を呼び出せば良いと思います。

2020-07-16 00:56 UTC, backpaper0 commented on src/main/java/nablarch/core/repository/di/config/externalize/AnnotationComponentDefinitionLoader.java
> +        ResourceClassHandler classHandler = new ResourceClassHandler(container, newComponentCreator(), this.getClass().getClassLoader());
`getClass()`だけ`this.`が付いています。取っちゃいましょう。

2020-07-16 01:02 UTC, backpaper0 requested changes
みました。

2020-07-16 02:10 UTC, kumagoro1202 commented on src/main/java/nablarch/core/repository/di/config/ConstructorInjectionComponentCreator.java
> +     * @param annotation アノテーション
https://github.com/nablarch/nablarch-core-repository/pull/16/commits/08aeac03b80968eec9709f6c6297a752d91ff299#diff-82d67eef73e113773f8d9ee986a35bc9R102

2020-07-16 02:12 UTC, kumagoro1202 commented on src/main/java/nablarch/core/repository/di/config/ConstructorInjectionComponentCreator.java
> +     * @param annotation アノテーション
https://github.com/nablarch/nablarch-core-repository/pull/16/commits/a1879ee2d53ed7cd897ff884527651c30553faf9#diff-82d67eef73e113773f8d9ee986a35bc9R118

2020-07-16 02:13 UTC, kumagoro1202 commented on src/main/java/nablarch/core/repository/di/config/externalize/AnnotationComponentDefinitionLoader.java
> +        for (Resources resources : ResourcesUtil.getResourcesTypes(basePackage)) {
https://github.com/nablarch/nablarch-core-repository/pull/16/commits/5c4c89a6f3004decc3eddf73664bfc61548303b6

2020-07-16 02:13 UTC, kumagoro1202 commented on src/main/java/nablarch/core/repository/di/config/externalize/AnnotationComponentDefinitionLoader.java
> +        ResourceClassHandler classHandler = new ResourceClassHandler(container, newComponentCreator(), this.getClass().getClassLoader());
https://github.com/nablarch/nablarch-core-repository/pull/16/commits/5c4c89a6f3004decc3eddf73664bfc61548303b6

2020-07-16 06:46 UTC, backpaper0 approved these changes

2020-07-16 06:49 UTC, merged