コンポーネント定義から存在しない環境依存値を参照した場合に例外を送出する
nablarch/nablarch-core-repository pull request #25
Opened 2021-02-19 10:48 UTC by kumagoro1202

https://github.com/nablarch/nablarch-core-repository/pull/24/files#r579024102
IDEが自動で整形していました。次回から気をつけます。

https://github.com/nablarch/nablarch-core-repository/pull/24/files#r579025032
`isAllowEmptyValue` に移動しました。

https://github.com/nablarch/nablarch-core-repository/pull/24/files#r579030213
`value == null` と `isAllowEmptyValue(container)` は一緒には評価出来ません。
&&でつないでしまうとelseの条件が`value != null || !isAllowEmptyValue(container)` になってしまいます。
`value == null` の場合に `isAllowEmptyValue(container)` の評価によって分岐させるので入れ子になります。

https://github.com/nablarch/nablarch-core-repository/pull/24/files#r579031566
`allowEmptyValue instanceof String && Boolean.parseBoolean((String) allowEmptyValue)` で事足りることに気づいたのでそうしました。

https://github.com/nablarch/nablarch-core-repository/pull/24/files#r579032954
既存がExceptionの型だけでOKにしていたので倣いましたが適切でないので、それぞれテストケースに合わせたメッセージでアサートするよう既存部分含めて修正しました。

2021-02-20 00:18 UTC, kiyohome requested changes

2021-02-20 00:18 UTC, kiyohome commented on src/test/java/nablarch/core/repository/di/DiContainerTest.java
> +            assertThat(e.getMessage(), containsString("property value was not found."));
「parameter = xxxx」をアサートに含めてない理由ありますか？
parameterが正しく出てないとこのメッセージ見ても対応するのに時間かかるので、paramterが大事だと思います。

2021-02-23 23:40 UTC, kumagoro1202 commented on src/test/java/nablarch/core/repository/di/DiContainerTest.java
> +            assertThat(e.getMessage(), containsString("property value was not found."));
仰る通りプロパティ名やコンポーネント名も必要なのでテストケースに追加しました。

2021-03-01 04:44 UTC, kiyohome approved these changes

2021-03-01 04:44 UTC, kiyohome commented
LGTM!

2021-03-01 04:45 UTC, merged